[package]
name = "platformer"
version = "0.1.0"
authors = ["Brandon Pfeifer <bnpfeife@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.14.0"
glam = "0.14.0"
lewton = "0.10.2"
png = "0.16.8"
rayon = "1.5.0"
sdl2 = "0.34.4"
sdl2-sys = "0.34.4"
